-- MoviCloud SPA - SQL schema (database-agnostic)
-- If your database does not support IDENTITY, replace with AUTO_INCREMENT/serial as needed.

CREATE TABLE users (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  email VARCHAR(255) NOT NULL UNIQUE,
  password_hash VARCHAR(255) NOT NULL,
  role VARCHAR(50) NOT NULL DEFAULT 'admin',
  status VARCHAR(50) NOT NULL DEFAULT 'active',
  name VARCHAR(120),
  phone VARCHAR(40),
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP,
  last_login TIMESTAMP
);

CREATE TABLE captchas (
  id VARCHAR(36) PRIMARY KEY,
  answer_hash VARCHAR(255) NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  expires_at TIMESTAMP
);

CREATE TABLE spa_settings (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  spa_name VARCHAR(200) NOT NULL,
  address VARCHAR(300),
  contact_number VARCHAR(40),
  email VARCHAR(255),
  logo_url VARCHAR(400),
  opening_time VARCHAR(10),
  closing_time VARCHAR(10),
  slot_duration_min INT NOT NULL DEFAULT 60,
  max_appointments_per_day INT NOT NULL DEFAULT 12,
  buffer_time_min INT NOT NULL DEFAULT 10,
  auto_confirm_booking BOOLEAN NOT NULL DEFAULT TRUE,
  email_notifications BOOLEAN NOT NULL DEFAULT TRUE,
  appointment_reminders BOOLEAN NOT NULL DEFAULT TRUE,
  payment_cash BOOLEAN NOT NULL DEFAULT TRUE,
  payment_upi BOOLEAN NOT NULL DEFAULT FALSE,
  tax_percentage DECIMAL(6, 2) NOT NULL DEFAULT 0,
  discount_percentage DECIMAL(6, 2) NOT NULL DEFAULT 0,
  updated_at TIMESTAMP
);

CREATE TABLE spa_working_days (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  spa_settings_id BIGINT NOT NULL,
  day_of_week SMALLINT NOT NULL,
  is_open BOOLEAN NOT NULL DEFAULT TRUE,
  FOREIGN KEY (spa_settings_id) REFERENCES spa_settings(id)
);

CREATE TABLE membership_tiers (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  name VARCHAR(100) NOT NULL,
  note VARCHAR(200),
  price_multiplier DECIMAL(6, 2) DEFAULT 1.0,
  status VARCHAR(50) NOT NULL DEFAULT 'active'
);

CREATE TABLE clients (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  full_name VARCHAR(160) NOT NULL,
  email VARCHAR(255) UNIQUE,
  phone VARCHAR(40) UNIQUE,
  address VARCHAR(300),
  age INT,
  status VARCHAR(50) NOT NULL DEFAULT 'active',
  contact_method VARCHAR(20) NOT NULL DEFAULT 'email',
  membership_tier_id BIGINT,
  preferences_notes TEXT,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP,
  FOREIGN KEY (membership_tier_id) REFERENCES membership_tiers(id)
);

CREATE TABLE staff (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  full_name VARCHAR(160) NOT NULL,
  role_title VARCHAR(120),
  department VARCHAR(120),
  placement VARCHAR(120),
  status VARCHAR(50) NOT NULL DEFAULT 'active',
  email VARCHAR(255),
  phone VARCHAR(40),
  permissions_level INT DEFAULT 1,
  permissions_label VARCHAR(120),
  onboarding_status VARCHAR(50),
  is_therapist BOOLEAN NOT NULL DEFAULT FALSE,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP
);

CREATE TABLE therapist_profiles (
  staff_id BIGINT PRIMARY KEY,
  specialty VARCHAR(160),
  bio TEXT,
  booking_priority VARCHAR(50),
  availability_status VARCHAR(50),
  image_url VARCHAR(400),
  FOREIGN KEY (staff_id) REFERENCES staff(id)
);

CREATE TABLE rooms (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  name VARCHAR(160) NOT NULL,
  type VARCHAR(120),
  status VARCHAR(50) NOT NULL DEFAULT 'available',
  capacity INT,
  temperature_c DECIMAL(5, 2),
  humidity_pct DECIMAL(5, 2),
  notes TEXT,
  image_url VARCHAR(400),
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP
);

CREATE TABLE services (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  name VARCHAR(160) NOT NULL,
  description TEXT,
  category VARCHAR(120),
  duration_min INT NOT NULL,
  price DECIMAL(10, 2) NOT NULL,
  status VARCHAR(50) NOT NULL DEFAULT 'active',
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP
);

CREATE TABLE offers (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  title VARCHAR(160) NOT NULL,
  description TEXT,
  price DECIMAL(10, 2),
  original_price DECIMAL(10, 2),
  status VARCHAR(50) NOT NULL DEFAULT 'active',
  starts_at TIMESTAMP,
  ends_at TIMESTAMP,
  tags VARCHAR(200)
);

CREATE TABLE appointments (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  client_id BIGINT NOT NULL,
  therapist_id BIGINT,
  room_id BIGINT,
  service_id BIGINT,
  status VARCHAR(50) NOT NULL DEFAULT 'scheduled',
  start_at TIMESTAMP NOT NULL,
  end_at TIMESTAMP,
  duration_min INT,
  notes TEXT,
  created_by BIGINT,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP,
  FOREIGN KEY (client_id) REFERENCES clients(id),
  FOREIGN KEY (therapist_id) REFERENCES staff(id),
  FOREIGN KEY (room_id) REFERENCES rooms(id),
  FOREIGN KEY (service_id) REFERENCES services(id),
  FOREIGN KEY (created_by) REFERENCES users(id)
);

CREATE TABLE notifications (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  appointment_id BIGINT,
  channel VARCHAR(40),
  recipient VARCHAR(255),
  template VARCHAR(120),
  status VARCHAR(50),
  payload TEXT,
  sent_at TIMESTAMP,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (appointment_id) REFERENCES appointments(id)
);

CREATE TABLE payments (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  appointment_id BIGINT,
  client_id BIGINT,
  amount DECIMAL(10, 2) NOT NULL,
  tax_amount DECIMAL(10, 2) DEFAULT 0,
  discount_amount DECIMAL(10, 2) DEFAULT 0,
  method VARCHAR(40),
  status VARCHAR(50),
  paid_at TIMESTAMP,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (appointment_id) REFERENCES appointments(id),
  FOREIGN KEY (client_id) REFERENCES clients(id)
);

CREATE TABLE payment_line_items (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  payment_id BIGINT NOT NULL,
  service_id BIGINT,
  name VARCHAR(160),
  qty INT NOT NULL DEFAULT 1,
  price DECIMAL(10, 2) NOT NULL,
  FOREIGN KEY (payment_id) REFERENCES payments(id),
  FOREIGN KEY (service_id) REFERENCES services(id)
);

CREATE TABLE loyalty_accounts (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  client_id BIGINT NOT NULL UNIQUE,
  points_balance INT NOT NULL DEFAULT 0,
  tier_label VARCHAR(80),
  updated_at TIMESTAMP,
  FOREIGN KEY (client_id) REFERENCES clients(id)
);

CREATE TABLE analytics_snapshots (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  period_start DATE NOT NULL,
  period_end DATE NOT NULL,
  revenue_services DECIMAL(12, 2),
  revenue_retail DECIMAL(12, 2),
  revenue_total DECIMAL(12, 2),
  retention_rate DECIMAL(6, 2),
  avg_ticket DECIMAL(10, 2),
  active_memberships INT,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE analytics_popular_treatments (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  snapshot_id BIGINT NOT NULL,
  service_id BIGINT,
  percent DECIMAL(6, 2),
  FOREIGN KEY (snapshot_id) REFERENCES analytics_snapshots(id),
  FOREIGN KEY (service_id) REFERENCES services(id)
);

CREATE TABLE analytics_lifecycle_heatmap (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  snapshot_id BIGINT NOT NULL,
  day_index INT NOT NULL,
  value INT NOT NULL,
  FOREIGN KEY (snapshot_id) REFERENCES analytics_snapshots(id)
);

CREATE TABLE ai_insights (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  title VARCHAR(200) NOT NULL,
  summary TEXT,
  priority VARCHAR(50),
  status VARCHAR(50),
  accuracy DECIMAL(6, 2),
  uplift DECIMAL(6, 2),
  impact VARCHAR(120),
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE ai_insight_actions (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  insight_id BIGINT NOT NULL,
  label VARCHAR(200),
  action_type VARCHAR(80),
  payload TEXT,
  FOREIGN KEY (insight_id) REFERENCES ai_insights(id)
);

CREATE TABLE audit_logs (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  actor_id BIGINT,
  action VARCHAR(120) NOT NULL,
  entity VARCHAR(120) NOT NULL,
  entity_id VARCHAR(120),
  before_data TEXT,
  after_data TEXT,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (actor_id) REFERENCES users(id)
);

CREATE INDEX idx_clients_name ON clients(full_name);
CREATE INDEX idx_clients_status ON clients(status);
CREATE INDEX idx_staff_status ON staff(status);
CREATE INDEX idx_rooms_status ON rooms(status);
CREATE INDEX idx_services_category ON services(category);
CREATE INDEX idx_appointments_start ON appointments(start_at);
CREATE INDEX idx_appointments_therapist ON appointments(therapist_id, start_at);
CREATE INDEX idx_appointments_room ON appointments(room_id, start_at);
CREATE INDEX idx_payments_client ON payments(client_id);
CREATE INDEX idx_notifications_sent ON notifications(sent_at);
CREATE INDEX idx_ai_insights_priority ON ai_insights(priority);
